"""add project table fix relationships

Revision ID: 014cc01019c3
Revises: d7a304eae295
Create Date: 2026-06-21 23:30:54.705959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '014cc01019c3'
down_revision: Union[str, Sequence[str], None] = 'd7a304eae295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_conversation_project_updated', 'chat_conversation', ['project_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_chat_conversation_project_id'), 'chat_conversation', ['project_id'], unique=False)
    op.drop_constraint(op.f('chat_conversation_ibfk_3'), 'chat_conversation', type_='foreignkey')
    op.create_foreign_key(None, 'chat_conversation', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('document_ibfk_2'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_ibfk_2'), 'document', 'project', ['project_id'], ['id'])
    op.drop_constraint(None, 'chat_conversation', type_='foreignkey')
    op.create_foreign_key(op.f('chat_conversation_ibfk_3'), 'chat_conversation', 'project', ['project_id'], ['id'])
    op.drop_index(op.f('ix_chat_conversation_project_id'), table_name='chat_conversation')
    op.drop_index('idx_conversation_project_updated', table_name='chat_conversation')
    # ### end Alembic commands ###
