"""rename thumbnail_url to thumbnai_key in document

Revision ID: c921367f43a3
Revises: 508db5064310
Create Date: 2026-06-21 12:49:25.149229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c921367f43a3'
down_revision: Union[str, Sequence[str], None] = '508db5064310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('thumbnail_key', sa.Text(), nullable=False))
    op.drop_column('document', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('thumbnail_url', mysql.TEXT(), nullable=False))
    op.drop_column('document', 'thumbnail_key')
    # ### end Alembic commands ###
