"""add project table

Revision ID: d7a304eae295
Revises: b31cf85ae736
Create Date: 2026-06-21 23:00:50.509592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a304eae295'
down_revision: Union[str, Sequence[str], None] = 'b31cf85ae736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_name', name='uq_project_user_name')
    )
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.create_index('ix_project_user_id_created_at', 'project', ['user_id', 'created_at'], unique=False)
    op.add_column('chat_conversation', sa.Column('project_id', sa.String(length=36), nullable=False))
    op.create_foreign_key(None, 'chat_conversation', 'project', ['project_id'], ['id'])
    op.add_column('document', sa.Column('project_id', sa.String(length=36), nullable=False))
    op.create_index(op.f('ix_document_project_id'), 'document', ['project_id'], unique=False)
    op.create_foreign_key(None, 'document', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_index(op.f('ix_document_project_id'), table_name='document')
    op.drop_column('document', 'project_id')
    op.drop_constraint(None, 'chat_conversation', type_='foreignkey')
    op.drop_column('chat_conversation', 'project_id')
    op.drop_index('ix_project_user_id_created_at', table_name='project')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
